name: 'Smart CI trigger using label as environment name'
description: 'Github action which ensures that only one pull request has the environment label at a time, and outputs if the CI environment (label) should be deployed.'
inputs:
  action-github-token:
    description: 'the github token provided by the action which will not trigger other actions'
    required: true
  personal-github-token:
    description: 'the personal token that the user should use'
    required: true
  env-label:
    description: 'The label corresponding to the CI environment'
    required: true
outputs:
  should-deploy:
    description: 'returns "true" if the current ref should be deployed on the CI environment, "false" otherwise'
runs:
  using: 'node12'
  main: 'index.js'
