name: 'Smart CI triggers'
description: 'Smartly trigger CI based on the use of pull request labels'
inputs:
  action-github-token:
    description: 'the github token provided by the action which will not trigger other actions'
    required: true
  personal-github-token:
    description: 'the personal token needed to automatically trigger workflows'
    required: true
  env-label:
    description: 'The label corresponding to the CI environment'
    required: true
outputs:
  should-deploy:
    description: 'returns "true" if the current ref should be deployed on the CI environment, "false" otherwise'
runs:
  using: 'node16'
  main: 'index.js'
