on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [synchronize, labeled, unlabeled]
  issues:
    types: [unlabeled]
  repository_dispatch:
    types: [trigger_main_workflow]

jobs:
  deploy_stage1_job:
    runs-on: ubuntu-latest
    name: deploy on stage1
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: check deploy stage1
        uses: ./ # Uses an action in the root directory
        id: check-deploy-stage1
        with:
          action-github-token: ${{ secrets.GITHUB_TOKEN }}
          personal-github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          env-label: 'stage1'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.STAGING_SLACK_WEBHOOK }}
          SLACK_USERNAME: App deploy notifier
          SLACK_ICON_EMOJI: 
          SLACK_TITLE: Deployed ${{ github.repositoy }} ${{ github.ref }} on staging
          MSG_MINIMAL: ref, commit

