on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled, unlabeled]
  issues:
    types: [unlabeled]
  repository_dispatch:
    types: [trigger_main_workflow]

jobs:
  deploy_stage1_job:
    runs-on: ubuntu-latest
    name: deploy on stage1
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: check deploy stage1
        uses: ./ # Uses an action in the root directory
        id: check-deploy-stage1
        with:
          action-github-token: ${{ secrets.GITHUB_TOKEN }}
          personal-github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          env-label: 'stage1'
      - name: actual deploy on stage1
        if: ${{ steps.check-deploy-stage1.outputs.should-deploy == 'true' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.STAGING_SLACK_WEBHOOK }}
          SLACK_USERNAME: staging botte
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: "$GITHUB_REPOSITORY ($GITHUB_REF) has been deployed on the staging"
